### ISSUE TITLE
שם קטגוריה ארוך מידי

### ISSUE THREAD

**Issue by RinatBrandes** [BuStRaMa/Hebrew.kbvault#16]
נסיתי להכניס את כל המלל הבא לקטגוריה וקיבלתי שגיאה בשמירה
יש לבצ חסימה מעבר לכמות התווים המותרת כמות בשם מאמר

בדיקת שם קטגוריה - מה האורך הניתן להקליד 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 12345678901234567890 1234567890 1234567890 1234567890 א 1234567890 ב 1234567890 ג 1234567890 ד 1234567890 ה 1234567890 ו 1234567890 ז 1234567890 ח 1234567890 ט

**Comment by BuStRaMa** [comment]
הוגבלה כותרת המאמר ל80 תווים
כותרת קטגוריה ל50 תווים
